#!/usr/bin/env bash
# Create an isolated worktree that shares builds and upstreams.
#
# One worktree per branch, zero duplicated heavy state: every worktree points
# its Cargo `target/` at one shared directory, so dependency artifacts build
# once instead of once per worktree — and `upstream/` checkouts link back here
# instead of re-downloading gigabytes. Run from anywhere inside the repo:
#
#   ./scripts/new-worktree.sh <name> [base-ref]
#
# creates `../dovetail-<name>` on branch `<name>` from `base-ref` (default
# HEAD). Concurrent builds in two worktrees serialize on the shared target
# lock; that is the price of sharing, and evidence comes from CI anyway.
#
# The generated `.cargo/config.toml` holds machine-local absolute paths and is
# never committed — see `/.cargo/` in `.gitignore`. Point `DOVETAIL_TARGET_DIR`
# elsewhere to share differently.
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: scripts/new-worktree.sh <name> [base-ref]" >&2
  exit 2
fi
name="$1"
base="${2:-HEAD}"

top="$(git rev-parse --show-toplevel)"
parent="$(dirname "$top")"
dest="$parent/dovetail-$name"
shared="${DOVETAIL_TARGET_DIR:-$parent/.dovetail-target}"

if [[ -e "$dest" ]]; then
  echo "::error::$dest already exists" >&2
  exit 1
fi

git -C "$top" worktree add "$dest" -b "$name" "$base"

mkdir -p "$dest/.cargo" "$shared"
{
  echo "# Generated by scripts/new-worktree.sh. Never committed:"
  echo "# every worktree builds here so dependencies compile once."
  echo ""
  echo "[build]"
  echo "target-dir = \"$shared\""
} > "$dest/.cargo/config.toml"

linked=0
for checkout in "$top"/upstream/*/; do
  checkout="${checkout%/}"
  base_name="$(basename "$checkout")"
  if [[ -d "$checkout/.git" && ! -e "$dest/upstream/$base_name" ]]; then
    ln -s "$checkout" "$dest/upstream/$base_name"
    linked=$((linked + 1))
  fi
done

echo "worktree: $dest (branch $name)"
echo "target-dir: $shared"
echo "upstream checkouts linked: $linked"
echo "next: ./scripts/fetch-upstream.sh (only what the links missed), then cargo run -p dovetail-prompt -- next"
